Document: e-editor
Title: Debian e-editor Manual
Author: <insert document author here>
Abstract: This manual describes what e-editor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/e-editor/e-editor.sgml.gz

Format: postscript
Files: /usr/share/doc/e-editor/e-editor.ps.gz

Format: text
Files: /usr/share/doc/e-editor/e-editor.text.gz

Format: HTML
Index: /usr/share/doc/e-editor/html/index.html
Files: /usr/share/doc/e-editor/html/*.html
